/* LOGIN */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_PENDING = 'LOGIN_PENDING';

/* REGISTRATION */
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const REGISTRATION_PENDING = 'REGISTRATION_PENDING';

/* LOGOUT */
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';

/* MENU */
export const MENU_SUCCESS = 'MENU_USER_SUCCESS';
export const MENU_FAILURE = 'MENU_USER_FAILURE';
export const MENU_PENDING = 'MENU_PENDING';

/* UPDATE USER*/
/* MENU */
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
