/* USER*/

/* LOGIN */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_PENDING = 'LOGIN_PENDING';

/* REGISTRATION */
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const REGISTRATION_PENDING = 'REGISTRATION_PENDING';

/* LOGOUT */
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';

/* MENU */
export const MENU_SUCCESS = 'MENU_USER_SUCCESS';
export const MENU_FAILURE = 'MENU_USER_FAILURE';
export const MENU_PENDING = 'MENU_PENDING';

/* UPDATE USER*/
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';

/* USER END*/

/* ADMIN */

/* GET ALL USERS*/
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';

/* DELETE USER */
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

/* GET USER BY ID */
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE';

/* UPDATE USER */
export const UPDATE_USER_ADMIN_SUCCESS = 'UPDATE_USER_ADMIN_SUCCESS';
export const UPDATE_USER_ADMIN_FAILURE = 'UPDATE_USER_ADMIN_FAILURE';

/* DELETE MEAL*/
export const DELETE_MEAL_SUCCESS = 'DELETE_MEAL_SUCCESS';
export const DELETE_MEAL_FAILURE = 'DELETE_MEAL_FAILURE';

/* UPDATE MEAL*/
export const UPDATE_MEAL_SUCCESS = 'UPDATE_MEAL_SUCCESS';
export const UPDATE_MEAL_FAILURE = 'UPDATE_MEAL_FAILURE';

/* ADD MEAL*/
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAILURE = 'ADD_MEAL_FAILURE';

/* GET MEAL BY ID*/
export const GET_MEAL_BY_ID_SUCCESS = 'GET_MEAL_BY_ID_SUCCESS';
export const GET_MEAL_BY_ID_FAILURE = 'GET_MEAL_BY_ID_FAILURE';

/* GET ALL TABLES*/
export const GET_ALL_TABLES_SUCCESS = 'GET_ALL_TABLES_SUCCESS';

/* DELETE TABLE */
export const DELETE_TABLE_SUCCESS = 'DELETE_TABLE_SUCCESS';

/* GET TABLE BY ID*/
export const GET_TABLE_BY_ID_SUCCESS = 'GET_TABLE_BY_ID_SUCCESS';

/* UPDATE TABLE */
export const UPDATE_TABLE_SUCCESS = 'UPDATE_TABLE_SUCCESS';

/* CREATE TABLE*/
export const CREATE_TABLE_SUCCESS = 'CREATE_TABLE_SUCCESS';

/* ADMIN END*/

/* MANAGER */

/* TABLE FREQUENCY*/
export const TABLE_FREQUENCY_SUCCESS = 'TABLE_FREQUENCY_SUCCESS';

/* RESERVATION TRAFFIC */
export const RESERVATION_TRAFFIC_SUCCESS = 'RESERVATION_TRAFFIC_SUCCESS';

/* MEAL ORDERS */
export const MEAL_ORDERS_SUCCESS = 'MEAL_ORDERS_SUCCESS';

/* USER RESERVATIONS */
export const  USER_RESERVATIONS_SUCCESS = 'USER_RESERVATIONS_SUCCESS';

/* MANAGER END*/

